version: "3"

tasks:
  default:
    cmds: [task --list]
    silent: true

  clean:
    desc: Remove executables
    cmds: [rm -rf bin/]

  build:
    desc: Build executables
    cmds:
      - mkdir -p bin
      - go build -o ./bin ./...

  lint:
    desc: Lint code
    cmds: [golangci-lint run]

  fix-lint:
    desc: Removes lint
    cmds: [golangci-lint run --fix]
